apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-demo-ns
  labels:
    app: flask-web
spec:
  selector:
    app: flask-web
  ports:
    - protocol: TCP
      port: 8484
      targetPort: 8484
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo-deployment
  namespace: flask-demo-ns
  labels:
    app: flask-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: flask-hello-world
        image: bonao99/flask-hello-world
        ports:
        - containerPort: 8484